version: '3.9'

services:
  postgres:
    container_name: 'postgresdb'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=ordersdb
    ports:
      - '5432:5432'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
  api:
    container_name: 'orders-api'
    image: orders/api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=host=postgres;Port=5432;user id=postgres;password=changeit;database=ordersdb;
      - ConnectionStrings__ServiceBus=
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling
    build:
      context: ./src
      dockerfile: Dockerfile-Api
    ports:
      - '5000:80'
  service:
    container_name: 'orders-processor'
    image: orders/processor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=host=postgres;Port=5432;user id=postgres;password=changeit;database=ordersdb;
      - ConnectionStrings__ServiceBus=
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling
    build:
      context: ./src
      dockerfile: Dockerfile-Processor