version: '3.9'

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  postgres:
    container_name: 'postgresdb'
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=ordersdb
    ports:
      - '5432:5432'
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
  api:
    container_name: 'orders-api'
    image: orders/api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=host=postgres;Port=5432;user id=postgres;password=changeit;database=ordersdb;
      - ConnectionStrings__ServiceBus=
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling
    build:
      context: ./src
      dockerfile: Dockerfile-Api
    ports:
      - '5000:80'
    depends_on: 
      - rabbitmq
      - postgres
    links:
      - rabbitmq
      - postgres
  service:
    container_name: 'orders-processor'
    image: orders/processor
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=host=postgres;Port=5432;user id=postgres;password=changeit;database=ordersdb;
      - ConnectionStrings__ServiceBus=
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling
    build:
      context: ./src
      dockerfile: Dockerfile-Processor
    depends_on:
      - rabbitmq
      - postgres
    links:
      - rabbitmq
      - postgres