FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["Orders.Api/Orders.Api.csproj", "Orders.Api/"]
COPY ["Orders.Contracts/Orders.Contracts.csproj", "Orders.Contracts/"]

RUN dotnet restore "Orders.Api/Orders.Api.csproj"

COPY . .
RUN dotnet publish -c Release -o /app Orders.Api/Orders.Api.csproj

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS publish
WORKDIR /app

COPY --from=build /app ./

ENTRYPOINT ["dotnet", "Orders.Api.dll"]